# Generated by Django 4.2.5 on 2023-09-27 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0004_remove_event_submission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
