# Generated by Django 4.2.5 on 2023-11-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0005_alter_calendar_user_alter_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
