# Generated by Django 4.2.5 on 2023-11-25 03:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0006_rename_assigned_date_event_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Event', max_length=60, verbose_name='Event Title')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='EditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Event', max_length=60, verbose_name='Event Title')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='submission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='google_calendar.submittype'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='Assignment', max_length=60, verbose_name='Assignment Title'),
        ),
    ]
