# Generated by Django 4.2.5 on 2023-09-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='submission_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='google_calendar.submittype'),
        ),
    ]
