name: Django Coverage
on:
  push:
    branches:
      - main
      - COV
  pull_request:
    branches:
      - main
      - COV

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            sudo apt-get update

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          cd ScheduleBuilder
          pip install -r requirements.txt

      - name: Run Google Calendar Tests with Coverage
        env:
          CAL_ID: c_6ed17073345c64d5b392f5a8ef7b4a62938f12c8fc5fecfa4b7256ef88acad28@group.calendar.google.com
        run: |
          cd ScheduleBuilder
          python manage.py makemigrations
          python manage.py migrate
          cd account
          pytest --cov=./ --cov-report=xml regtests.py

      - name: Run Account Tests with Coverage
        env:
          CAL_ID: c_6ed17073345c64d5b392f5a8ef7b4a62938f12c8fc5fecfa4b7256ef88acad28@group.calendar.google.com
        run: |
          cd ScheduleBuilder/account
          pytest --cov=./ --cov-report=xml test.py
          
      - name: Combine Coverage Reports
        run: |
          cd ScheduleBuilder
          coverage combine google_calendar/coverage.xml account/coverage.xml
          coverage xml -o combined_coverage.xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./ScheduleBuilder/combined_coverage.xml
          fail_ci_if_error: true
