name: Django Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: ls -l ./ScheduleBuilder 
              pip install -r /ScheduleBuilder/requirements.txt
        working-directory: ${{ github.workspace }}
