name: Django Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
        runs-on: ubuntu-latest
        steps:
          - name: Install dependencies
            run: |
                sudo apt-get update
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
              ls
              pip install -r ScheduleBuilder/requirements.txt
